---
title: "Recharge Event Comparisons"
author: "Alysa M. Yoder"
date: "June 27, 2018"
output: 
 html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
library(knitr)
library(here)
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      error = FALSE, 
                      cache = TRUE, 
                      eval = TRUE)
```

```{r}

## Writing a df for all recharge event timeframes in 2013WY
event_pre13 <- data.frame(matrix(ncol = 4, nrow = 3))
cnames <- c("Event Number", "Start", "End", "Length")
colnames(event_pre13) <- cnames

#event_pre13$`Event Number` <- seq(1,3,1)
event_pre13$Start <- as.POSIXct(c("12/18/2012 22:00:00", "12/23/2012 02:45:00", "01/05/2013 21:45:00"), 
                                format = "%m/%d/%Y %H:%M")
event_pre13$End <- as.POSIXct(c("12/19/2012 20:00:00", "12/28/2012 14:00:00", "01/09/2013 02:00:00"), 
                                format = "%m/%d/%Y %H:%M")
#event_pre13$Length <- event_pre13$End - event_pre13$Start #leaving empty so they'll be consistent 
```


```{r pre removal dates, include=FALSE}
## Writing a df for all recharge event timeframes in 2014WY
event_pre14 <- data.frame(matrix(ncol=4, nrow=4))
cnames <- c("Event Number", "Start", "End", "Length")
colnames(event_pre14) <- cnames
#event_pre14[ ,1] <- seq(1,4,1) #leaving blank, more efficient to do all at once after rbind
#these are start times of each event 
event_pre14[ ,2] <- as.POSIXct(c("02/09/2014 23:00:00", 
                                 "03/01/2014 02:00:00", 
                                 "03/02/2014 18:45:00", 
                                 "04/02/2014 15:45:00"),
                               format = "%m/%d/%Y %H:%M")
#these are end times of each event 
event_pre14[ ,3] <- as.POSIXct(c("02/12/2014 18:00:00", 
                                 "03/06/2014 15:30:00", 
                                 "03/08/2014 14:00:00", 
                                 "04/05/2014 16:00:00"),
                               format = "%m/%d/%Y %H:%M")
#event_pre14[ ,4] <- event_pre14[ ,3] - event_pre14[ ,2] #leaving these empty for now so units will be consistent
```


```{r, include=FALSE}
## Writing a df of all pre-removal recharge event timeframes
event_pre <- rbind(event_pre13, event_pre14)
event_pre$`Event Number` <- seq(1,nrow(event_pre), 1)
event_pre$Length <- event_pre$End-event_pre$Start

```


```{r, include=FALSE}
## Get integrated discharge volume for each pre-removal event
### Get Data
library(here)
library(dplyr)
library(kableExtra)
mb <- read.csv(here::here("data", "mich_bar_cms_all.csv"), stringsAsFactors = FALSE)
mb$Date <- as.POSIXct(mb$Date, format = "%m/%d/%Y %H:%M")
```


```{r post removal, include=FALSE}
### This comprises 2015-2017
event_post <- data.frame(matrix(ncol=4, nrow=19))
cnames <- c("Event Number", "Start", "End", "Length")
colnames(event_post) <- cnames
#event_post[ ,1] <- seq(1,4,1) #leaving blank, more efficient to do all at once after rbind
#these are start times of each event 
event_post[ ,2] <- as.POSIXct(c("12/12/2014 23:00:00", 
                                 "12/20/2014 14:45:00", 
                                 "02/08/2015 03:45:00", #last of 2015WY events
                                 "12/22/2015 23:15:00", 
                                "01/19/2016 00:15:00",
                                "01/23/2016 14:45:00",
                                "01/30/2016 12:00:00",
                                "02/19/2016 04:45:00",
                                "03/05/2016 13:45:00", #last of 2016WY events
                                "11/28/2016 19:45:00",
                                "12/11/2016 1:30:00",
                                "01/04/2017 19:00:00",
                                "01/18/2017 18:45:00",
                                "02/04/2017 07:15:00",
                                "02/20/2017 14:15:00",
                                "03/22/2017 15:00:00",
                                "04/07/2017 04:30:00",
                                "04/13/2017 19:00:00",
                                "04/18/2017 15:00:00"),
                               format = "%m/%d/%Y %H:%M")
#these are end times of each event 
event_post[ ,3] <- as.POSIXct(c("12/14/2014 16:45:00", 
                                 "12/22/2014 14:00:00", 
                                 "02/12/2015 15:45:00", #last of 2015WY events
                                 "12/23/2015 12:45:00",
                                "01/21/2016 02:30:00",
                                "01/25/2016 04:30:00",
                                "02/02/2016 12:00:00",
                                "02/19/2016 20:45:00",
                                "03/17/2016 13:00:00", #last of 2016WY events
                                "11/29/2016 03:00:00",
                                "12/21/2016 12:45:00",
                                "01/12/2017 14:00:00",
                                "01/24/2017 07:00:00",
                                "02/11/2017 09:00:00",
                                "02/22/2017 14:15:00",
                                "03/23/2017 16:15:00",
                                "04/09/2017 19:45:00", 
                                "04/15/2017 01:30:00",
                                "04/20/2017 03:45:00"), 
                               format = "%m/%d/%Y %H:%M")
#write df of all start and end dates w/proper headings
event_post$`Event Number` <- seq(1,nrow(event_post), 1)
event_post$Length <- event_post$End-event_post$Start
```

```{r combine pre and post event timestamps, include=FALSE}
event <- rbind(event_pre, event_post)
```


```{r, include=FALSE}
### Put Integrated Discharge Values into a df
source("Qvol_fxn.R") #calculates cumulative discharge throughout a time period w/Mich.Bar data
source("evsub_fxn.R") #creates df with data from the specified time interval 

#add event ID column to DF for cleaner result communication
EventID <- seq(1,nrow(event),1)

Qdat <- data.frame(EventID) # event number in event_pre corresponds to the row numbers in Qdat. 

for (row in 1:nrow(event)) {
 Qdat[row, 2] <- Qvol(ev_data = evsub(event[row,2], event[row,3]))
}
colnames(Qdat) <- c("Event #", "Integrated Discharge m^3^")
```


```{r, include=FALSE}
### Results
kable(Qdat, format = "markdown", caption = "Integrated Flow Volume at Michigan Bar during Pre-Levee Removal Recharge Events (m^3)") 
#to make a LaTex table, change format from "markdwon" to "latex"
```

```{r, include = FALSE}
# Process
## Get Groundwater Level Data
adata <- read.csv(here::here('data', 'allsets.csv'))
adata <- adata[-c(1,3,15,17:31)] #removing index numbers, MW-13, Oneto-Ag (confined), and Nathan's text 
```

```{r, include = FALSE}
## Estimate Recharge for each pre-removal event
source("rech_fxn.R")
source("rechcalc_gwl_format.R")
startdat <- list()
enddat <- list()
for (ev in 1:nrow(event_pre)) {
  startdat[[ev]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, Date == as.character(event_pre$Start[ev])))))
  enddat[[ev]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, Date == as.character(event_pre$End[ev])))))
}
prerech <- matrix(nrow = length(EventID[1:7]), ncol = 2)
prerech <- as.data.frame(prerech)
prerech[,1] <- EventID[1:7]
for (ev in 1:nrow(event_pre)) {
 prerech[ev,2] <- rechvol(begin = startdat[[ev]], end = enddat[[ev]], plot_title = "Pre-Removal Recharge Events")
}
colnames(prerech) <- c("Event ID", "Recharge Volume (m3)")
kable(prerech, format = "markdown")
```




```{r, include = FALSE}
## Estimate recharge for post-removal events 
##Actual recharge calc for post-removal events
source("rech_fxn.R")
source("rechcalc_gwl_format.R")
startdat <- list()
enddat <- list()
for (n in 1:nrow(event_post)) {
  startdat[[n]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, Date == as.character(event_post$Start[n])))))
  enddat[[n]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, Date == as.character(event_post$End[n])))))
}
postrech <- matrix(nrow = 19, ncol = 2)
postrech <- as.data.frame(postrech)
EventID_post <- seq(8,nrow(event_post)+7,1)
postrech[,1] <- EventID_post
for (ev in 1:nrow(event_post)) {
 postrech[ev,2] <- rechvol(begin = startdat[[ev]], end = enddat[[ev]], plot_title = "Post-Removal Recharge Events")
}
colnames(postrech) <- c("Event ID", "Recharge Volume (m3)")
kable(postrech, format = "markdown")
```

# Recharge Estimate for Each Event, 2013-2017
```{r result table}
allev <- rbind(event_pre,event_post)
allev$`Event Number` <- NULL
vols <- rbind(prerech, postrech)
rech <- cbind(allev, vols)
pre_string <- rep("pre", 7)
post_string <- rep("post", 19)
kable(rech, format = "markdown")
rech$id <- as.factor(c(pre_string,post_string))
rech$ld <- as.numeric(rech$Length/24)
rech$ld <- round(rech$ld, digits = 1)
```
# Plot of Recharge Volumes of Each Event
* Use range slider to zoom in on time periods. 
* Hover over bars to display the event length and recharge volume. 
```{r}
library(plotly)
width = as.vector.factor(rech$Length*100)
t <- plot_ly(rech) %>%
  add_trace(x=mb$Date, y=mb$MiBarCMS, type = "scatter", mode = "lines", name="Discharge (cms)", yaxis="y2",
            line = list(color = '#45171D', width = 0.5))%>% 
  add_trace(x = rech$Start[1:7], y = rech$`Recharge Volume (m3)`[1:7], type ='bar', 
             name = "pre levee removal", marker = list(color = "#43a2ca"), 
            hoverinfo = 'text', text = ~paste(rech$ld[1:7], 'days'), width = width[1:7]) %>%
  add_trace(x = rech$Start[8:26], y=rech$`Recharge Volume (m3)`[8:26], type = 'bar',
            name = "post levee removal", marker = list(color= "#a8ddb5"), 
            hoverinfo = 'text', text = ~paste(rech$ld[8:26], 'days'), width = width[8:26]) %>%
  rangeslider() %>%
  layout(
    hovermode = 'compare',
    title = "Recharge Volume of Each Event",
    xaxis = list(title = 'Time', zeroline = FALSE),
    yaxis = list(title = 'Recharge Volume (m3)', showgrid = FALSE, zeroline = FALSE),
    yaxis2 = list(side = 'right', overlaying = 'y', title ='Discharge (cms)', showgrid = FALSE, zeroline = FALSE))
   # legend = list(x=0.1, y = 0.9))
t
#need to look at these results relative to MB hydrograph

```

# Additional Recharge Event Volume Plots
```{r plot rech vols}
library(ggplot2)
library(plyr)
library(plotly)

ggplot(data = rech) + 
  geom_point(aes(x=rech$Start, y=rech$`Recharge Volume (m3)`)) + 
  theme_bw() + 
  labs(title = "Recharge Volume of Event (m3)", x = "Date", y = "Recharge Volume (m3)")

#test w/barplot
barwidth <- as.vector(rech$Length)
barplot(height = rech$`Recharge Volume (m3)`, width = barwidth, 
        col = c("red","red","red","red","red","red","red","blue",
                "blue","blue","blue","blue","blue","blue","blue",
                "blue","blue","blue","blue","blue","blue","blue",
                "blue","blue","blue","blue","blue","blue","blue"), 
                xlab="Time", ylab="Recharge Volume (m3)", 
                main = "Recharge Volume for Each Event", 
                sub = "Pre and Post Levee Removal",
                legend.text = TRUE,
                border = NA)
```

# Recharge Volume per Cumulative River Discharge, Pre vs. Post
```{r agreement test}
agree <- cbind(rech$`Event ID`, rech$`Recharge Volume (m3)`, rech$id, Qdat$`Integrated Discharge m^3^`)
colnames(agree) <- c('ID', 'RechVol', 'prevpost', 'Cumul.Dis')
agree <- as.data.frame(agree)
agree$RechPerDis <- agree$RechVol/agree$Cumul.Dis

#put the df in order of smallest Q to largest
agreesort <- agree[order(agree$Cumul.Dis),]
#load new df with the pairs of pre post events that are most similar considering Qvol
library(here)
ag <- read.csv(here::here("agree.csv"))
library(plotly)
at <- plot_ly(agree) %>%
  add_trace(x=~ID[1:7], y = ~RechPerDis[1:7], type = 'scatter', mode = 'marker') %>%
  add_trace(x=~ID[8:26], y=~RechPerDis[8:26], type = 'scatter', mode = 'marker')

agr <- plot_ly(ag) %>%
  add_trace(x=~pre, y=~post, type = "scatter", opacity = .8, 
            marker = list(size =20, color = "#458B74"), name = 'pre v post') %>%
  add_trace(x=c(0,5.5e-4), y = c(0,5.5e-4), type = "scatter", mode = 'lines', 
            line = list(color = '#000000'), name = "1:1") %>%
  layout(title = 'Pre vs. Post Agreement for Events with Similar Cumulative Discharge Volumes')
agr
```
