#Why doesn't git let me stage... 
#Git issue fixed after force quitting R for the 10th time, deleting the index.lock file in .git, and deleting the large CosumnesGO_SharedFiles2 file
  #Will just have to move individual files if I use Nathan's stuff, file is too screwed up and probably has dup file names with my COsumnesGO_SharedFiles2...
  #...and maybe other files in the directory which would be even worse. 