---
title: "Comparisons to MODFLOW Results"
author: "Alysa M. Yoder"
date: "June 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
begin <- read.csv('modflow_3_16_2013_compare.csv')

 # Determine area of entire raster
  # Raster has 68523 cells
  y_bound <- distm(c(-121.3914, 38.2917), c(-121.3914, 38.31267))
  x_bound <- distm(c(-121.3914, 38.2917), c(-121.3686, 38.2917))
  # Calculate area in m^2
  area <- y_bound * x_bound
  # Total area is 4656185 m^2
  
  # define coordinate system
  coordinates(begin) <- ~ long + lat
  
  # load spatial domain to interpolate over
  grid <- raster(begin, ncols=100, nrows=100)
  
  # interpolate highs
  idw_begin <- gstat(formula = begin$level~1, locations = begin, nmax = 8, set = list(idp=2))
  idw_begin <- interpolate(grid, idw_begin)

  # subtract to find net water levels throughout the event
  event_vol <- idw_begin
  
  # import outline of boundary, as a set of points in lat/long that we generated in ArcMap as a digitized polyline
  bound <- read.csv("bound_table.csv", stringsAsFactors = FALSE, header = TRUE)
  bound_pts <- bound[,c(4,5)]
  colnames(bound_pts) <- c('x', 'y')
  
  # convert raster to SPDF, or at least get some coords
  event_pts <- coordinates(event_vol)[!is.na(values(event_vol)),]
  colnames(event_pts) <- c('x', 'y')
  
  # clip event idw by the innundation extent generated form our digitized polyline in ArcMap
  library(splancs)
  temp <- rasterToPoints(event_vol) %>% as.data.frame()
  event_clip <- temp[inout(event_pts, bound_pts), ]
  colnames(event_clip) <- c('x','y','z')
  
  # plot idwevent_clip as a heatmap
  library(viridis)
  library(magrittr)
  event_clip %>% 
    ggplot() +
    geom_tile(aes(x,y, fill = z)) +
    coord_fixed(1) +
    scale_fill_viridis(name="Event Recharged Head (m)") +
    theme_void()
  
  coordinates(event_clip) <- ~ x + y
  gridded(event_clip) <- TRUE
  event_rast <- raster(event_clip, "z")
  plot(event_rast)
  title(main = "Change in Water Levels 2015WY (m)")
  


```
