---
title: "OD 2016-17 Recharge Estimates"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE

author: Amy Yoder
---

## Setup
* bullet 1
* bullet 2

```{r, message = FALSE, warning = FALSE, results = "hide"}
# setwd()
setwd("~/GitHub/OD_recharge")


# load packages
packagelist = list("ggplot2", "colorspace", "reshape2", "tidyverse", "knitr", "sp", 
                   "rgdal", "raster", "gstat", "dismo", "spMC", "formatR", "dplyr", "magrittr")
lapply(packagelist, library, character.only = TRUE)

# read in data frames, convert to SPDF
low <- read.csv("R_input_low_1617.csv")
high <- read.csv('R_input_high_1617.csv')
coordinates(high) <- ~ long + lat
coordinates(low) <- ~ long + lat
```

### Plot SWL

```{r}
# plot surface water levels

low %>% as.data.frame %>% 
  ggplot(aes(long, lat)) + geom_point(aes(size=levellow), color="blue", alpha=3/4) + 
  ggtitle("Lowest Surface Water Level (m)") + coord_equal() + theme_bw()

```

## Kriging Recharge Estimates

```{r}
library(gstat)

# krige low----

# variogram
lzn.vgm <- variogram(log(low$levellow*-1)~1, low) # calculate sample variogram values
lzn.fit <- fit.variogram(lzn.vgm, model=vgm(psill = 10, "Sph", range = NA, kappa = 0.5)) # fit model
plot(lzn.vgm, lzn.fit)

# load spatial domain to interpolate over
grid <- raster(low, ncols=100, nrows=100)
g<-as(grid, 'SpatialGrid')

# krige
k <- gstat(formula = low$levellow~1, locations = low, model = lzn.fit)
kriged <- predict(k,g)
plot(kriged)
plot(low, add = T)


#krige high----

# variogram 
h.vgm <- variogram(log(high$levelhigh)~1, data = high) 
h.fit <- fit.variogram(h.vgm, model=vgm(psill = .1, "Lin", range = NA))
plot(h.vgm, h.fit)

# krige
kh <- gstat(formula = high$levelhigh~1, locations = high, model = h.fit)
krigedh <- predict(kh, g)
plot(krigedh)
plot(high, add = T)

# krige difference----
rash <- raster(krigedh)
rasl <- raster(kriged)
krige1617 <- rash-rasl
plot(krige1617, col = rainbow(100), main = expression("2016-17 Wet-Season Cumulative "*Delta*" Head(m) w/Kriging"), 
     alpha = .5)
plot(high, add = T)

# krige recharge estimate----
ac_per_cell <- 1136/10000
krige1617feet <- krige1617*3.28084
sum_krige_ft <- cellStats(krige1617feet, 'sum')
krig_rech1617_acft <- sum_krige_ft*ac_per_cell

```


## IDW Recharge Estimates

```{r}
# idw low ----
gs<-gstat(formula = low$levellow~1, locations = low, nmax=8, set=list(idp=2))
idw<-interpolate(grid, gs)
plot(idw, main = 'Lowest SWL (m)')
plot(low, add=T)

# idw high----
high %>% as.data.frame %>% 
  ggplot(aes(long, lat)) + geom_point(aes(size=levelhigh), color="blue", alpha=3/4) + 
  ggtitle("Highest Surface Water Level (m)") + coord_equal() + theme_bw()
hi <- gstat(formula = high$levelhigh~1, locations = high, nmax=8, set=list(idp=2))
idw_h <- interpolate(grid, hi)
plot(idw_h, main = 'Highest SWL(m)')
plot(high, add=T)

# inverse distance weighting difference----
idw1617 <- idw_h - idw

plot(idw1617, main = expression("2016-17 Wet-Season Cumulative "*Delta*" Head(m)"), col = rainbow(100), alpha = 0.5)
plot(high, add=T)

# idw recharge estimate----
idw1617feet <- idw1617*3.28084
ac_per_cell <- 1136/10000
sum_idw_ft <- cellStats(idw1617feet, 'sum')
rech1617_acft <- sum_idw_ft*ac_per_cell

```

## Add basemap w/ggmap. Plots not working.
```{r}
library(ggmap)
b <- bbox(low)
(low.b1 <- ggmap(get_map(location = b))) #download map for Oneto-Denier 
```

## Add basemap w/leaflet

```{r}
# add basemap w/leaflet
library(raster)
library(leaflet)

# idw
glimpse(idw1617)
idw1617@crs <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
pal <- colorNumeric(c("#9e0142", "#d53e4f", "#f46d43", "#fdae61", "#fee08b", "#e6f598", "#abdda4", 
"#66c2a5", "#3288bd", "#5e4fa2"), values(krige1617), na.color = "transparent")
pal2 <- colorNumeric(c("#9e0142", "#d53e4f", "#f46d43", "#fdae61", "#fee08b", "#e6f598", "#abdda4", 
"#66c2a5", "#3288bd", "#5e4fa2"), values(idw1617), na.color = "transparent")

leaflet() %>% addTiles %>% 
  addProviderTiles(providers$OpenTopoMap) %>% 
  addRasterImage(idw1617, colors = pal2, opacity = 0.85) %>%
  addLegend(pal=pal2, values = values(idw1617), title = "IDW Recharge Estimates 2016-17")

# krig
glimpse(krige1617)
krige1617@crs <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

leaflet() %>% addTiles %>% 
  addProviderTiles(providers$OpenTopoMap) %>% 
  addRasterImage(krige1617, colors = pal, opacity = 0.85) %>%
  addLegend(pal=pal, values = values(krige1617), title = "Kriged Recharge Estimates 2016-17") 
```

