---
title: "Water Year Rech Vol per Flow Vol"
author: "Alysa M. Yoder"
date: "June 28, 2018"
output: 
 html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
library(knitr)
library(here)
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      error = FALSE, 
                      cache = TRUE, 
                      eval = TRUE)
```



```{r, include = FALSE}
## Create df with begin and end dates for each WY's recharge period
WYtf <- data.frame(matrix(ncol=4, nrow=4))
colnames(WYtf) <- c("WY", "Start", "End", "Length")
WYtf$WY <- seq(2014,2017,1)
WYtf$Start <- as.POSIXct(c("2014-02-09 12:00:00",
                         "2014-12-04 12:00:00",
                         "2015-12-10 12:00:00",
                         "2016-10-19 12:00:00"))
WYtf$End <- as.POSIXct(c("2014-05-10 12:00:00",
                          "2015-04-12 12:00:00",
                          "2016-03-18 12:00:00",
                          "2017-02-11 12:00:00"))
WYtf$Length <- WYtf$End-WYtf$Start
```


```{r, include = FALSE}
## Create df with total discharge vol for each WY recharge term
#call functions from 'event_compare.Rmd' 
source("Qvol_fxn.R")
source("evsub_fxn.R")
WY <- seq(2014,2017,1)
QdatWY <- data.frame(WY) # event number in event_pre corresponds to the row numbers in Qdat. 

for (row in 1:nrow(WYtf)) {
 QdatWY[row, 2] <- Qvol(ev_data = evsub(WYtf[row,2], WYtf[row,3]))
}
colnames(QdatWY) <- c("WY", "Integrated Discharge m^3")
kable(QdatWY)
```
## Get Groundwater Level Data
```{r}

adata <- read.csv(here::here('data', 'allsets.csv'))
adata <- adata[-c(1,3,15,17:31)] #removing index numbers, MW-13, Oneto-Ag (confined), and Nathan's text 
```
#Generate WY Change in Head Rasters
```{r}
#call functions from 'event_compare.Rmd' 
source("rech_fxn.R")
source("rechcalc_gwl_format.R")
#make list of start and end date
Start <- list()
End <- list()
#for loop to format data for rechvol
for (n in 1:nrow(WYtf)) {
  Start[[n]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, 
    Date == as.character(WYtf$Start[n])))))
  End[[n]] <- rechcalc_gwl_format(as.data.frame(t(subset(adata, 
    Date == as.character(WYtf$End[n])))))
}

WYrech <- matrix(nrow = 4, ncol = 2)
WYrech <- as.data.frame(WYrech)
EventID_WY <- seq(1,4,1)
WYrech[,1] <- EventID_WY

for (ev in 1:nrow(WYtf)) {
 WYrech[ev,2] <- rechvol(begin = Start[[ev]], end = End[[ev]], plot_title = "Water Year Recharge Events")
}

colnames(WYrech) <- c("Event ID", "Recharge Volume (m3)")
kable(WYrech, format = "markdown")

#test to find area of clipped raster
toad <- raster(here::here("latflow_rasters", "1hi.tif"))
proj4string(toad)<- CRS("+proj=longlat +datum=WGS84")
```

## Recharge Vol per Integrated Discharge Vol
```{r}
rech <- read.csv(here::here("data", "clipped_2014_17_rechargeVols.csv"), header = TRUE, sep = ",")
rech <- rech[1:4,1:4] #remove NA values, don't know why they're being created

anlz <- cbind(QdatWY, rech$MidRecharge)
anlz$rech_per_qvol <- anlz$`rech$MidRecharge`/anlz$`Integrated Discharge m^3`
colnames(anlz) <- c("WY", "Integrated Discharge m^3", "Recharge (m^3)", "Recharge per Cumulative Q")
kable(anlz, format = "markdown")
library(ggplot2)
ggplot(anlz, aes(x=anlz$WY)) + 
  geom_bar(aes(y = anlz$`Recharge per Cumulative Q`), fill = "blue", stat = "identity") +
  geom_bar(aes(y = anlz$`Recharge (m^3)`/1e13), fill = "red", stat = "identity") +
  scale_y_continuous(sec.axis = sec_axis(~.*1e13, name = "Recharge (red)")) +
  labs(y = "Recharge per Integrated Q (blue)", 
       x = "Water Year",
       colour = "Legend") +
  theme_light()

#ggplot(anlz, aes(x =WY, y = anlz$`Integrated Discharge m^3`)) + geom_bar(stat = "identity", fill = "pink") +
#  theme_light()
library(plotly)
#p <- plot_ly(anlz, x = WY, y = anlz$`Integrated Discharge m^3`, type = 'bar', name = 'QVol') %>%
#  add_trace(y = anlz$`Recharge (m^3)`, name = 'Recharge Vol') %>%
#  add_trace(y = anlz$`Recharge per Cumulative Q`, name = "Rech per Qvol") %>% 
#  layout(yaxis = list(title = 'Value', type = "log"), barmode = 'group')
#p
```
